### ISSUE TITLE
Missing source code

### ISSUE THREAD

**Issue by dwedigital** [the-road-to-learn-react/the-road-to-react#102]
All the source code links in the kindle edition appear to be dead e.g. [example from kindle chapter](https://codesandbox.io/p/devbox/github/the-road-to-learn-react/hacker-stories/tree/2024-lifting-state/?file=/src/App.jsx)

**Comment by rwieruch** [comment]
Hm, I just tried and it worked for me.

![Screenshot 2024-06-12 at 18 52 02](https://github.com/the-road-to-learn-react/the-road-to-react/assets/2479967/add74700-f8f6-40c1-bc8f-20b0839d5c58)

**Comment by dwedigital** [comment]
Hey @rwieruch just realised the issue is: `Either the GitHub authentication token is expired or it is missing authorization(s)`

**Comment by rwieruch** [comment]
Do you need to sign in to CodeSandbox?

**Comment by dwedigital** [comment]
@rwieruch I am an idiot, so sorry. I was logged in code sandbox as use it myself! If I go incognito the links work fine, sorry to waste your time! Love the book.
