### ISSUE TITLE
Question concerning createRef and useRef

### ISSUE THREAD

**Issue by astridx** [the-road-to-learn-react/the-road-to-react#21]
Is line 10 in the file https://github.com/the-road-to-learn-react/the-road-to-react/blob/master/manuscript/react-legacy/imperative-react.md correct?

> Recently, the React team introduced **React's createRef** as the  latest equivalent to a function component's useRef hook:

If I am right `createRef` was introduced in 16.3 and `useRef` in 16.7.

Please have a look, if my translation of this sentence is OK: https://github.com/astridx/the-road-to-react-german/pull/21/files

**Comment by rwieruch** [comment]
Good point. Didn't remember that createRef got introduced that much earlier! 

One thing though: If I am not mistaken, useRef was introduced in 16.8. with all the other React hooks.

See change for English version here: https://github.com/the-road-to-learn-react/the-road-to-react/commit/841a80228ad45021968f27ee388df811f36a25df

CC @LiJiahaoCoder and @sujinleeme
