### ISSUE TITLE
Diff in react-styling - chapters

### ISSUE THREAD

**Issue by astridx** [the-road-to-learn-react/the-road-to-react#24]
> Confirm the changes `from the last section`.

Is this sentence (or the link) in the style-files correct? For example here: https://github.com/the-road-to-learn-react/the-road-to-react/blob/master/manuscript/react-styling/css.md

I changed it in the German version. I leave out the "`from the last section`": https://github.com/astridx/the-road-to-react-german/pull/22/files#diff-cec0b9770a1357078a8902c514cef05aR248

Is that OK or am I missing something?

**Comment by rwieruch** [comment]
Ah, you mean because it doesn't reference "the last section" in this case, right? That's correct, maybe I should be more explicit with the language here. 

I think it would best to refactor *all* the **Confirm the changes from the last section.** to **Confirm the changes.** What do you think?

**Comment by astridx** [comment]
> @rwieruch  I think it would best to refactor _all_ the **Confirm the changes from the last section.** to **Confirm the changes.** What do you think?


I haven't read everything yet. But so far there are only inconsistencies in the styling directory. That's why I would only change this here. Except for the SVG file. Here the changes relate to another branch. See my German translation: https://github.com/astridx/the-road-to-react-german/pull/32/files#diff-6b1810ffc4e0de106fd7cb85caa6ab31R81

**Comment by rwieruch** [comment]
It will happen again with the maintenance chapters. But yeah, good points! :)
