### ISSUE TITLE
Steps to translate a "The Road to ..." Book

### ISSUE THREAD

**Issue by rwieruch** [the-road-to-learn-react/the-road-to-react#58]
# Shoot me an E-Mail

- Shoot me an E-Mail at hello [at] rwieruch [dot] com and tell me your GitHub account and which book you want to translate into which language.

# Translation

- You will get an invite from me to a GitHub repository for the translated version of the book. 
- The GitHub repository should have the files from the English GitHub repository. From here start to translate the book file by file. The *Book.txt* file in the */manuscript* folder should give you the idea of the structure of the book.
- The */manuscript* folder has a *contributor.md* file where you can introduce yourself and your team as translators of the book. Don't forget to include this file in the *Book.txt* file if you decide to make use of it.
- Optional: You should have all the permissions to invite more people to the GitHub repository to help you.
- Optional: If you have questions, just open a GitHub Issue and ping me with @rwieruch 
- Optional: If you have suggestions on how to improve the original book, [open a GitHub Issue or Pull Request for it](https://github.com/the-road-to-learn-react/the-road-to-react).

Once you have finished the translation, continue with one or both of the next steps.

# Optional: Leanpub

- If you want to create PDF, MOBI, or EPUB files from your translated book on GitHub, create an account on [Leanpub](https://leanpub.com) and shoot me again an E-Mail with the information of your Leanpub account. 
- I will invite you as author to the translated version of the book. 
- On Leanpub, you can connect the book to your GitHub repository's master branch. After connecting your book, you can visit the "Preview"-tab to create your files.
- Optional: If you want to offer your book for free or as paid version on Leanpub, you are free to do it. Otherwise, using Leanpub for generating just the files is fine as well. If you decide for a paid version, you will receive 99% of the royalties. However, keep in mind that a free version has a far wider reach than a paid version. If you decide for a paid version, then a $19.99 may be reasonable (or maybe adjust the price to your countries purchasing power). On Leanpub, you can also offer the book for free but give people the option to pay something for it.
- Optional: If you want to modify the cover (add yourself as author, change the title to your language) of your book, shoot me an E-Mail again and I will give you an invite to my team on [Canva](https://www.canva.com/join/belt-piano-lovable). There you can clone the original cover and adjust it to your needs.

# Optional: GitHub

- Instead of creating a paid/free version on Leanpub, you can also just take the GitHub repository for others to read your translated book. However, the markdown is specific to Leanpub, so you may want to consider to generate a [GitHub readable markdown](https://github.com/the-road-to-learn-react/the-road-to-react/issues/57). Afterward, simply advertise your GitHub repository for people to read your book.

# Continuous Translation

- Over time I may introduce new chapters or improvements to the original book. I will ping you (the primary maintainer, not your team) in these PRs to integrate these changes in your translated book. Even though I think it's best to synchronize the books from time to time, you decide whether you have the capacities to do it and when to do it.

**Comment by rwieruch** [comment]
CC @astridx @LiJiahaoCoder @sujinleeme

**Comment by Jbnado** [comment]
Hi, are you still wanting to translate it? I would love to contribute and translate it to portuguese from Brazil.
