### ISSUE TITLE
Mention needed: React.StrictMode component in src/index.js renders twice leading to confusion

### ISSUE THREAD

**Issue by jazzinpark** [the-road-to-learn-react/the-road-to-react#60]
The output of code in section “Performance in React (Advanced)“, subsection “Don’t re-render if not needed” (pg. 154 (164 of 249) in pdf) has a possible source of confusion.

The `React.StrictMode` component stated in src/index.js renders twice for internal React debugging.
With this, the output from `console.log` becomes like following:
```
// initial render
B:App
B:App
B:List
// data fetching with loading
B:App
B:App
// re-rendering with data
B:App
B:App
B:List
```
-> "B:App" being logged twice instead once, which is different from the book.

Mentioning this would prevent confusion for people without the prior knowledge.

**Comment by rwieruch** [comment]
Thank you @jazzinpark 🎉
