### ISSUE TITLE
Clarification: Logical OR (||)

### ISSUE THREAD

**Issue by ddehart** [the-road-to-learn-react/the-road-to-react#70]
As someone not totally familiar with JavaScript, this expression in the React Side-Effects section was confusing:

`localStorage.getItem('search') || 'React'`

It might be worth clarifying that JavaScript returns the truthy operand in this expression and that it's short-circuited if `localStorage.getItem('search')` returns a truthy value. Or maybe link to the MDN article about [Logical OR](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_OR).

**Comment by rwieruch** [comment]
Good point! I will add this in the next edition. Thanks so much for your feedback @ddehart 👍
