### ISSUE TITLE
Mistaken positioning of rest and spread operators relative to the assignment operator.

### ISSUE THREAD

**Issue by rg12301** [the-road-to-learn-react/the-road-to-react#74]
#### Hey, Robin! It’s evident that you put a ton of time and effort into this book, and to keep it updated! While I was reading, something’s not quite matching up for me.

**`the-road-to-react/manuscript/react-modern/props-handling.md`** @ _line no. 308_
> ... Whereas the rest operator happens on the _right_ side of an assignment, the spread operator happens on the _left_ side.

**Shouldn't it be:**
> ... Whereas the rest operator happens on the **left** side of an assignment, the spread operator happens on the **right** side.

**Comment by rwieruch** [comment]
Yes, you are completely right here! Thanks :) I will fix this!
