### ISSUE TITLE
Foreword typos

### ISSUE THREAD

**Issue by javelwill** [the-road-to-learn-react/the-road-to-react#78]
Hi Robin, I read the Foreword of the book and identified the following typos (Some are minor, but I included them nonetheless).

1. ("will be explained for you" => "will be explained to you", p. i, para. 1)
2. ("real world" => "real-world", p. i, para. 1)
3. ("large scale" => "large-scale", p. ii, para. 1)
4. ("I find it a fulfilling seeing students thrive" => "I find it fulfilling to see students strive", p. ii, para. 2)
5. ("helping companies creatings" => "helping companies creating", p. ii, para. 3)
6. ("code audits/review" => "code audits/reviews", p. ii, para. 3)
7. ("large scale" => "large-scale", p. ii, para. 3)
8. ("extra large" => "extra-large", p. iii, para. 4)
9. ("only applies to" => "only apply to", p. iv, para. 2)
10. ("large scale" => "large-scale", p. ii, para. 3)
11. ("basic grasp about JS" => "basic grasp of JS", p. v, para. 1)
12. ("Non Javascript Developers" => "Non-Javascript Developers", p. v)
13. ("be more familiar than others about the different" => "be more familiar than others with the different")
14. ("the fundamentals about JavaScript" => "the fundamentals of JavaScript")
15. ("These days UI/UX are moving" => "These days UI/UX is moving", p. v, para. 5
16. ("the essential parts in a React application" => "the essential parts of a React application ", p. v, para. 6)
17. ("well rounded" => "well-rounded", p. v, para. 6)

**Comment by rwieruch** [comment]
Keep them coming! Thanks @javelwilson minor typos are good too! :)

**Comment by rwieruch** [comment]
If you don't want to write all typos out in a GitHub issue, you can create Pull Requests right away if you want too. Up to you! :)

**Comment by javelwill** [comment]
You're welcome @rwieruch. I will create pull requests instead :)
