### ISSUE TITLE
Improvements on mmw Review

### ISSUE THREAD

**Issue by rwieruch** [the-road-to-learn-react/the-road-to-react#89]
Hi @mmw I am not sure if I am addressing the right person here, but I think I found your review on The Road to React on Amazon and it really stood out to me. So I have taken it to heart for the next edition of the book and give my best to make it a better book!

---------

Improvements for [React State](https://github.com/the-road-to-learn-react/the-road-to-react/blob/master/manuscript/react-modern/state.md) and  its two images [0][1] which do not show up on GitHub.

- get rid of 10% code changes
- remove long explanation of array destructuring and add more in-depth explanation about useState

[0] https://github.com/the-road-to-learn-react/the-road-to-react/blob/master/manuscript/images/react-usestate.png
[1] https://github.com/the-road-to-learn-react/the-road-to-react/blob/master/manuscript/images/react-state.png

---------

Explain the Why. As example, the new [React List section](https://github.com/the-road-to-learn-react/the-road-to-react/blob/master/manuscript/react-modern/lists.md) with its key explanation + image [2].

[2] https://github.com/the-road-to-learn-react/the-road-to-react/blob/master/manuscript/images/react-keys-performance.png

---------

- general improvements: merge code snippets with small diffs
- give readers the choice to try it themselves first, before presenting them the solution

---------

A bit of context: I think The Road to React was a great book when it taught class components. The migration towards React Hooks happened in one swoop, because people demanded it, but at this time of my life I had my first kid and could not keep up with the quality for the rewrite. However, I am back at getting things right with this new edition, so I hope that I can address all the flaws people like you noticed. Thanks for the valuable feedback!

PS.: In this evolving market of self-published books it's really tough as a none native speaker. I had quality checks from several proofreaders over the last years and all of the book's editions, but it's always difficult to rate their outcome, because they should know better than me. But I will give it once again to a proofreader/editor once I finish this new edition!

Thanks again for your valuable feedback! I give my best to make this book awesome :-)

**Comment by mmw** [comment]
Hello @rwieruch, unfortunately you do not have the correct person. I checked out your book on Amazon and it seems like a great resource, I see that it is well reviewed. Congratulations on your success and best of luck with your work :)

**Comment by rwieruch** [comment]
Okay, it was worth a shot :) Thanks for your kind words!
