### ISSUE TITLE
Hooks, State Management sections make book more valuable

### ISSUE THREAD

**Issue by jonyahmed19** [the-road-to-learn-react/the-road-to-react#91]
## Shortcomings are hooks, state management section

I read the book. It has beginner friendly explanation.  
However, I expected special chapters on **hooks & state** management. 
If Robin add these 2 sections in next version, that will increase book's value.

Thanks

**Comment by rwieruch** [comment]
Thanks for the suggestions @jonyahmed19 ! 💯
