### ISSUE TITLE
Typos and grammatical errors in Road to React and a couple tutorials

### ISSUE THREAD

**Issue by ghost** [the-road-to-learn-react/the-road-to-react#92]
Global search-and-replace if you can because this was in a bunch of the web tutorials:  "so called" should be "so-called" (add hyphen)

Web tutorial "react-pass-props-to-component"
Event though => Even though
When props can only => Since props can only
Both, the Headline and the Description => Both the Headline and the Description        (remove comma after Both)
However, could also use => However, we could also use   (add "we")
which is in between of the tags => which is in between the tags    (remove "of")
you don't need to pass props, in this case the user, multiple levels => you don't need to pass props - in this case the user - multiple levels   (replacing commas with hyphens)

Web tutorial "conditional-rendering-react/"
The article => This article
to null oder undefined => to null or to undefined
advice to use it => advise using it
It works, however => It works; however,    (replace comma with semi-colon and add comma after however)
recommend to avoid => recommend avoiding
renders, because => renders because    (no comma)

Web tutorial "javascript-reducer"
aren't touch => aren't touched

Web tutorial "react-context"
wrong in giving => wrong with giving
why not learning => why not learn

Web tutorial "react-render-props"
Firstly => First
and see how this => and see what this
But it hasn't to be the name => But it doesn't have to be the name
in between of the currency => in between the currency
It would be quite similar => It would be quite familiar
If using a render prop => If you are using a render prop

Web tutorial:  If you can do a global search, I wrote these two down but didn't write the page, so I'm not sure where they came from:
It's worth to note => It's worth noting
may wants => may want

Book "Road to React" on Kindle::

p.68 React Props:  "props, however" => "props; however"  (most of the time, "however" is preceded by a semi-colon instead of a comma since it is usually starting a new sentence)

p.69 methods =>method's (add apostrophe)

p.69 books implements => book implements    (book is singular)

p.85 between readable and conciseness => between readability and conciseness

p.88 Try yourself for some time figuring out => Spend some time on your own figuring out

p.88 input field, we see => input field do we see

p.96 While it's here not => While here it's not

p.102 keep over for => save for

p. 103 easiest to reason about => easiest to understand

p.104 First of all =>   omit this phrase, since you don't have a "second of all"

p.104 returns an array and props => returns an array whereas props

p.104 object hence => object; hence    (add semicolon)

p.104 hence the we need => hence we need

p.104 fitting operation => appropriate operation.

So p.104 Answer should read: a React Hook like useState returns an array whereas props are an object; hence we need to apply the appropriate operation for the underlying data structure.

p.106 HTML element's => HTML elements   (remove apostrophe)

p.118 Search component, input field and label, should => Search component - input field and label - should

p.135 manipulate (e.g. removing an item) it later => manipulate it (e.g. removing an item) later      ("it" goes before the parentheses)

p.139 which is in charge to execute => which is in charge of executing

p.158 (here an item's identifier`) => remove the back-tic after identifier

p.163 we changed ti state => we changed the state

p.171 same data structure for a story for the sample stories => same data structure for the sample stories

p.171 anything in the Item component, and it's => anything in the Item component.  It's

p.173 to play around in contrast => to play around with in contrast

p.173 serve-side => server-side   (add the 'r' on serve)

p.178 refactor the code once => refactor the code upfront

p.178 get all the explanation afterword => provide the explanations afterward    (and note the "s" at the end of explanations)

p.178 The refactoring contains moving => The refactoring consists of moving

p.180 but it is good use case => but it is a good use case   (add "a")

p.182 its internals is out => its internals are out

p.182 fluctuant => fluctuating

p.182 and will execute => and executes

p.187 how to install a axios => how to install axios   (remove "a")

p.187 consider to compensate the removal => consider compensating for the removal

p. 198 There will be for sure questions => There will for sure be questions

p.198 However, I kept the selection to a none overwhelming opinionated minimum =>  However, in my opinion, I kept the selection to a non-overwhelming minimum

p.199 an premature optimization => a premature optimization  ("an" should be "a")

p.199 or a obstacle => or an obstacle      ("a" should be "an")

p.199 less used these days, however, => less used these days; however,  (replace comma with semicolon before 'however')

**Comment by rwieruch** [comment]
Oh my god, this is awesome @cjfreedman Wow! You did really touch everything from book to tutorials 🚀  I need to allocate some time to go through this, but it's amazing. Thank you so much! How can I return the effort?

**Comment by ghost** [comment]
Sorry for the late reply, I took some time off since my son just came home from his university for the summer plus it was my other son’s birthday. 😊

I am new to React and inherited a project, so if I get stuck, I would appreciate being able to ask you a question, if that’s ok?

Also, as I said previously, it would be really helpful if you would create a table of contents or index or something on your website.  You have a TON of great content, but it is hard to find articles on specific topics and it is easy to miss other great articles with no easy way to browse.

Have a great day!
-Cynthia


From: Robin Wieruch ***@***.***>
Sent: Tuesday, June 7, 2022 12:57 AM
To: the-road-to-learn-react/the-road-to-react ***@***.***>
Cc: Freedman, Cynthia (ARC-AFS)[UNIVERSITIES SPACE RESEARCH ASSN] ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [the-road-to-learn-react/the-road-to-react] Typos and grammatical errors in Road to React and a couple tutorials (Issue #92)


Oh my god, this is awesome @cjfreedman<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcjfreedman&data=05%7C01%7Ccynthia.j.freedman%40nasa.gov%7Ce2c55fdaa72c4cbdc2ac08da485b4297%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C637901854058130197%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=QBeGCG3KIwzNVTUvbFD5tOBYfzPpmfUdv7BcFABGk8M%3D&reserved=0> Wow! You did really touch everything from book to tutorials 🚀 I need to allocate some time to go through this, but it's amazing. Thank you so much! How can I return the effort?

**Comment by jonyahmed19** [comment]
@cjfreedman You did a great job. We will get a better books in new release.
Thanks

**Comment by rwieruch** [comment]
Finally I had the time to include all your suggestions in the book. Thank you so much for all your hard work @cjfreedman 🚀 🤗
