### ISSUE TITLE
Small suggestion on requirements information

### ISSUE THREAD

**Issue by HCMF** [the-road-to-learn-react/the-road-to-react#99]
I started reading the book and in the beginning where you go over the requirements and mention you need Node and NPM, it think it might be a good idea to expand on what Node is. I know you provide the the link to the Node site, but for absolute beginners it might be helpful to expand a bit on what Node is, and how it relates to NPM. Thanks!

**Comment by rwieruch** [comment]
Thanks for the suggestion @HCMF ! 💯
